### PR TITLE
Pubcookie has been moved to github. Please update wiki.

### PR DESCRIPTION
**Pull request by ivandeex**
I moved Pubcookie module repository on github. Please update links in the wiki page.

### CODE REVIEW

**Comment by LinuxJedi** [comment]
Hi,

This is failing CI because there are 2 too many spaces after the github link. Can you please adjust and commit again?

Many thanks.

**Comment by aluttik** [comment]
@ivandeex: Thanks for helping us keep our wiki up to date 😃

We can't merge this yet because there's two too many spaces before the `|`. 
It's been a month now; would you like to delete the two spaces or can I?

**Comment by ivandeex** [comment]
@aluttik: Sorry for this delay. I've amended the failing commit. Please apply now.

**Comment by aluttik** [comment]
@ivandeex No problem, thanks again!

**Pull request merged**
