### PR TITLE
Update drupal.rst to support Debian based systems

### PR DESCRIPTION
**Pull request by dangreenisrael**
Added a line for people using Debian based systems

This is the result of a day of hair pulling  and 502 errors

### CODE REVIEW

**Comment by LinuxJedi** [comment]
good spot. Given that I don't know any OS that uses /tmp/phpfpm.sock I would be happy for you to actually just change that line rather than adding the comment

**Comment by dangreenisrael** [comment]
Done

**Comment by LinuxJedi** [comment]
Many thanks for your contribution!

**Comment by dangreenisrael** [comment]
Happy to help

**Pull request merged**
