### PR TITLE
nginx_mod_akamai_g2o moved to kaltura

### PR DESCRIPTION
**Pull request by erankor**
See here - https://github.com/refractalize/nginx_mod_akamai_g2o

### CODE REVIEW

**Comment by SirNexus** [comment]
Good One! Thanks for the Change!

**Comment by erankor** [comment]
Thanks @SirNexus, can let me know how long it takes for this change to propagate? 
I see my previous pull is not yet reflected on the site

**Comment by SirNexus** [comment]
@erankor, the change should be reflected within 24 hours.

**Comment by erankor** [comment]
Thanks, I see it now

**Pull request merged**
