### PR TITLE
Add nginx-stream-upsync-module, syncing upstreams from conf-server(etcd or consul)

### PR DESCRIPTION
**Pull request by xiaokai-wang**

### CODE REVIEW

**Comment by xiaokai-wang** [comment]
Sorry for the error and the same for the last commit.

A new pr and correct the error for last commit.

Thanks.

**Comment by LinuxJedi** [comment]
Thanks, but this time you appear to have added it twice :)

**Comment by xiaokai-wang** [comment]
That's two module, one for http and the other one for tcp. Please check again.

**Comment by LinuxJedi** [comment]
ah! Good point. I missed that. I think the table formatting is broken but I'll merge it and then fix accordingly. Many thanks.

**Comment by xiaokai-wang** [comment]
Thanks.

**Pull request merged**
