### PR TITLE
Fix for SPIP "urls arbos"

### PR DESCRIPTION
**Pull request by brunob**
As done here https://github.com/seenthis/hebergement/wiki/Configuration-nginx/7f196a49892ee360e90d8dc39d398e41c7e40eb4

### CODE REVIEW

**Comment by brunob** [comment]
Any news about a possible review ?

**Comment by alessfg** [comment]
Hiya! There's been some changes in ownership for this repo and I'll be taking charge of reviewing PRs moving forward. I have my hands full at the moment but rest assured I'll start working on the PR backlog as soon as I can 😄

**Comment by brunob** [comment]
@alessfg nice to see activity here :)

**Comment by alessfg** [comment]
Thanks for the fix @brunob!

**Comment by brunob** [comment]
u're welcome :)

**Pull request merged**
