### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by limithit**
I'm sorry I just submitted the wrong format

### CODE REVIEW

**Comment by SirNexus** [comment]
@limithit, the change is inconsistent with the current table on the wiki. I also reverted your last pull request because it had the same problem. My fault for missing it. If you would like to make the necessary changes, I can merge the request. Thanks!

**Comment by limithit** [comment]
I just want to submit a module, I did not expect to be so complicated, my English is not good, you can help me submit it

**Comment by SirNexus** [comment]
Hey @limithit, I just submitted a new pull request #341 that integrates successfully into the module page. Please make any changes you would like. Thanks!

**Comment by limithit** [comment]
@SirNexus  Thank you so much for your assistance.

**Comment by SirNexus** [comment]
I'm going to close this pull request because it conflicts with master.

**Pull request closed without merging**
