### PR TITLE
Create omeka-s.rst recipe

### PR DESCRIPTION
**Pull request by lguariento**
This is a working configuration for Omeka S.

### CODE REVIEW

**Comment by lguariento** [comment]
Does anyone know why the Travis CI build fails? I'm relatively new and wouldn't know where to start looking at possible causes.

**Comment by alessfg** [comment]
Hm looks like the error is at `omeka-s.rst:6: WARNING: Title underline too short.`

**Comment by alessfg** [comment]
New error -- `omeka-s.rst:12: WARNING: Explicit markup ends without a blank line; unexpected unindent`. Looks like you have to add a blank line between the code block declaration and the start of the NGINX config. Hopefully that's the last of the errors. (You can also check other recipes to see how they do it.)

**Comment by lguariento** [comment]
Ah OK, thanks. It seems that Travis doesn't like 'Omeka S' as title, so I edited as 'Omeka-S', and added the carriage return as you suggested.

**Comment by alessfg** [comment]
Hm still failing. Looks like the issue now is `WARNING: document isn't included in any toctree`. You'll have to include the recipe directory into `https://github.com/nginxinc/nginx-wiki/blob/master/source/start/index.rst`. And yes, there's already an Omeka recipe there, so you might have to slightly tweak the name. Maybe name it `omeka-s`?

**Comment by lguariento** [comment]
OK, I've called it Omeka-s in the file itself, and added omeka-s to the recipe directory (see https://github.com/nginxinc/nginx-wiki/pull/492). That build also fails, and the output is `null` so I don't know what's wrong now.

**Comment by alessfg** [comment]
It's back to title underline too short :/

**Comment by alessfg** [comment]
Pushed an update myself. Looks like tests are now passing so I'm gonna go ahead and merge 😄

**Comment by lguariento** [comment]
Thanks for your support and for updating/merging, good to see it go live!

**Pull request merged**
