### PR TITLE
Remove referer spam page until example works

### PR DESCRIPTION
**Pull request by pastudan**
Unfortunately the example provided does not work. The way it's configured currently will allow the listed domains but not any others. I don't see a way to do this without a regex negative lookahead :-/

cc @LinuxJedi @aluttik

### CODE REVIEW

**Comment by LinuxJedi** [comment]
No problem, it can be removed. But you also need to remove reference to it from source/start/index.rst to fix the CI failure.

**Comment by pastudan** [comment]
Thanks. Removed and tests are passing.

Also, if anyone is interested, I came up with an alternative solution: https://github.com/piwik/referrer-spam-blacklist/pull/217. It's a cronjob that auto updates your banned referrer blocks based on a user curated blacklist.

**Comment by LinuxJedi** [comment]
I suspect this is something you could do with nginScript or Lua.

Also couldn't you use valid_referers with its regex using your list of bad referrers and do?:
```
if ($invalid_referers != 1) {
    return 403;
}
```

Therefore the list of valid_referers becomes the list of invalid referers.

**Comment by pastudan** [comment]
You totally could.. That's actually a great way that I hadn't thought of. 

2 concerns though: 
1. you have to account for each domain and subdomain and therefore specify each domain twice. ie `badref.com *.badref.com`
1. there's no good way to disallow blocked domains without the `http://` prefix. `blocked` looks like it should take care of that, but doing that here would also block **every** request without `http://` in the referer which seems too aggressive

and using regex seems like it would have the same performance impact as my method, but would be less readable. (you must admit that specifying bad referers as valid_referers and then negating the `$invalid_ones` seems a bit backwards :-p)

**Comment by LinuxJedi** [comment]
You make some great points. Pull request approved anyway. Many thanks :)

**Pull request merged**
