### PR TITLE
Tutorial for IBM Cloud

### PR DESCRIPTION
**Pull request by KissConsult**
Step-By-step tutorial for deploying on IBM Cloud

### CODE REVIEW

**Comment by alessfg** [comment]
Thanks for recreating the PR! I noticed you uploaded a few images, however I don't know whether we support images (hence the failing tests). Let me try to figure it out and get back to you.

**Comment by KissConsult** [comment]
Allright thanks! 😄

**Comment by alessfg** [comment]
@KissConsult looks like it might be a path issue. Can you try using `/images/kubernetes-select.png` instead of `source/images/kubernetes-select.png`?

**Comment by alessfg** [comment]
I'm closing this since it's been almost a year since the last update. Feel free to reopen it if you so wish!

**Pull request closed without merging**
